function [] = light13g(w)
        rectangle('Position',[w-0.2,w-0.2,0.4,0.4],'Curvature',[1,1],...........
        'FaceColor','g','EdgeColor','g'),axis equal;
        rectangle('Position',[-w-0.2,-w-0.2,0.4,0.4],'Curvature',[1,1],..........
        'FaceColor','g','EdgeColor','g'),axis equal;