function [] = light13r(w)       
        rectangle('Position',[w-0.2,w-0.2,0.4,0.4],'Curvature',[1,1],...........
        'FaceColor','r','EdgeColor','r'),axis equal;
        rectangle('Position',[-w-0.2,-w-0.2,0.4,0.4],'Curvature',[1,1],..........
        'FaceColor','r','EdgeColor','r'),axis equal;